/**
 * AetherWave // ElevenLabs Vernacular Voice Audio Manager
 * Plays high-fidelity audio generated by ElevenLabs with sweet female voice (Sarah)
 * Falls back gracefully to Web Speech API if offline or on network failure.
 */

class VernacularVoicePlayer {
  private currentAudio: HTMLAudioElement | null = null;
  private audioCache = new Map<string, string>(); // text -> object URL
  private isSynthesizing = false;

  public async playVoice(
    text: string,
    options?: {
      dialect?: string;
      voiceId?: string;
      onStart?: () => void;
      onEnd?: () => void;
      onError?: (err: unknown) => void;
    }
  ): Promise<void> {
    this.stop();

    const cleanText = text.trim();
    if (!cleanText) return;

    try {
      // Check cache first
      let audioUrl = this.audioCache.get(cleanText);

      if (!audioUrl) {
        this.isSynthesizing = true;
        const res = await fetch('/api/voice/tts', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            text: cleanText,
            voiceId: options?.voiceId,
          }),
        });

        if (!res.ok) {
          throw new Error(`TTS server responded with ${res.status}`);
        }

        const blob = await res.blob();
        audioUrl = URL.createObjectURL(blob);
        this.audioCache.set(cleanText, audioUrl);
      }

      this.isSynthesizing = false;
      const audio = new Audio(audioUrl);
      this.currentAudio = audio;

      audio.onplay = () => {
        options?.onStart?.();
      };

      audio.onended = () => {
        options?.onEnd?.();
        this.currentAudio = null;
      };

      audio.onerror = (e) => {
        console.warn('Audio playback error, falling back to Web Speech API:', e);
        this.fallbackWebSpeech(cleanText, options);
      };

      await audio.play();
    } catch (err) {
      console.warn('ElevenLabs TTS fetch failed, triggering Web Speech fallback:', err);
      this.isSynthesizing = false;
      this.fallbackWebSpeech(cleanText, options);
    }
  }

  public stop(): void {
    if (this.currentAudio) {
      this.currentAudio.pause();
      this.currentAudio.currentTime = 0;
      this.currentAudio = null;
    }
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
  }

  public isPlaying(): boolean {
    return !!this.currentAudio && !this.currentAudio.paused;
  }

  private fallbackWebSpeech(
    text: string,
    options?: {
      dialect?: string;
      onStart?: () => void;
      onEnd?: () => void;
      onError?: (err: unknown) => void;
    }
  ) {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
      options?.onError?.(new Error('Speech synthesis not supported'));
      return;
    }

    try {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = options?.dialect || 'hi-IN';
      utterance.rate = 0.95;
      utterance.pitch = 1.1; // Slightly higher pitch for sweet female inflection

      utterance.onstart = () => options?.onStart?.();
      utterance.onend = () => options?.onEnd?.();
      utterance.onerror = (e) => options?.onError?.(e);

      window.speechSynthesis.speak(utterance);
    } catch (e) {
      options?.onError?.(e);
    }
  }
}

export const voicePlayer = new VernacularVoicePlayer();
